"""add_estado_to_seguimiento

Revision ID: 23bce1a6677b
Revises: 4cb467c98a4c
Create Date: 2025-12-18 00:32:36.493938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23bce1a6677b'
down_revision = '4cb467c98a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seguimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seguimiento', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
