"""Rename sesiones to num_sesiones in Planning

Revision ID: 578514139983
Revises: 75658bfda01e
Create Date: 2025-12-15 16:30:43.536442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578514139983'
down_revision = '75658bfda01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_sesiones', sa.Integer(), nullable=True))
        batch_op.drop_column('sesiones')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sesiones', sa.INTEGER(), nullable=True))
        batch_op.drop_column('num_sesiones')

    # ### end Alembic commands ###
