"""Initial migration after schema changes

Revision ID: 75658bfda01e
Revises: 
Create Date: 2025-12-15 16:30:09.142494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75658bfda01e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_ejercicio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_ejercicio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('autor', sa.VARCHAR(length=20), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('imagen_url', sa.VARCHAR(), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=500), nullable=True),
    sa.Column('jugadores', sa.INTEGER(), nullable=True),
    sa.Column('duracion', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['autor'], ['usuario.alias'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
